config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'notes_home#home'
  get 'noteskeeps/share_note'
  post 'noteskeeps/share_note'
  resources :noteskeeps
  # root 'noteskeeps#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/noteskeep.rb
class Noteskeep < ApplicationRecord
    belongs_to :user 

    # has_and_belongs_to_many :user
end

app/models/share.rb
class Share < ApplicationRecord
    # belongs_to :noteskeeps,:class_name => "Noteskeep",:foreign_key =>"noteskeep_id"
     
end

app/models/user.rb
class User < ApplicationRecord
  has_many :noteskeeps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  after_filter :store_action
  
  def store_action
    return unless request.get? 
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, noteskeeps_path)
    end
  end
  
  
  
end

app/controllers/notes_home_controller.rb
class NotesHomeController < ApplicationController
    def home
        
    end
end

app/controllers/noteskeeps_controller.rb
class NoteskeepsController < ApplicationController
     before_action :find_note, only: [:show,:edit,:destroy,:update]
     before_action :authenticate_user! ,only:[:new,:edit]
    
    def index
        @notes = Noteskeep.all.order("created_at DESC")
    end
    
    def show
        @share = Share.select(:user_shared_to,:user_shared_by,:share_type).where(noteskeep_id: params[:id] )
        @user = User.all

    end
    
    def new
        #@note = Noteskeep.new
        @note = current_user.noteskeeps.build
        @user = User.all
    end
    
    
    def create
        # @note = Noteskeep.new(notes_params)
        @note = current_user.noteskeeps.build(notes_params)
        if save_status = @note.save
            
            if save_status 
                @note_id = @note.id
                puts @note_id
                puts "******************"
                @share = Share.new(:user_shared_to => params[:user_shared_to], :user_shared_by => params[:user_shared_by], :share_type => params[:share_type],:noteskeep_id => @note_id)
                    flag_save = @share.save
            end
            
            redirect_to noteskeeps_path
        else
            render 'new'
        end
            
    end
    
    def edit
         @user = User.all
    end
    
    def update
        puts "@note"
        puts @note
        if @note.update(notes_params)
            redirect_to noteskeep_path(@note)
        else
            render 'edit'
        end
    end
     
    
    def destroy
        @note.destroy
        redirect_to noteskeeps_path
    end
    
    def share_note

        @share = Share.new(:user_shared_to => params[:user_shared_to], :user_shared_by => params[:user_shared_by], :share_type => params[:share_type],:noteskeep_id => params[:notekeep_id])
        flag_save = @share.save
        
        redirect_to noteskeeps_path
            

    end
    
    private
    
    def find_note
        @note = Noteskeep.find(params[:id])
    end
    
    def notes_params
       params.require(:noteskeep).permit(:title,:description) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_home_helper.rb
module NotesHomeHelper
end

app/helpers/noteskeeps_helper.rb
module NoteskeepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notekeeping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
  	<div clas="container-fluid">

  		<div class="navbar-header">
  		  <% if user_signed_in? %>
  			<%= link_to "Note-Keeping",noteskeeps_path, class: "navbar-brand" %> 
  			<%else%>
  			<%= link_to "Note-Keeping",root_path, class: "navbar-brand" %> 
  			<%end%>
  		

  		<ul class="nav navbar-nav">


            <% if user_signed_in? %>
        			<li><%= link_to "Add Note", new_noteskeep_path %></li>
        		<%end%>

  		  </ul>
  		 <ul class="nav navbar-nav navbar-right">
        
  			<% if user_signed_in? %>
  			<li>
  				<%= link_to "Sign_Out",  destroy_user_session_path, method: :delete%>
  			</li>

  			<% else %>
  			<li> <%= link_to "Log In", new_user_session_path %></li>
  			<li><%= link_to "Sign UP", new_user_registration_path%></li>
  			<% end %>
		    <% if user_signed_in? %>
        		<li>Logged in as <strong><%= current_user.email %></strong></li>
        <%end%>
  		</ul>

  	</div>
  	</div>
  </nav>
    
<% if notice %>
  <p class="alert alert-success" id ="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" id ="flash"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>
<script>
  $(document).ready(function () {   
    setTimeout(function () {   
      $('#flash').remove();  
      $('#notice').remove();
    }, 13000); 
  });
</script>

app/views/notes_home/home.html.erb
<div class="row">
	<div class="col-md-4">
            <h1>NOTE-KEEPING</h1>
	 <%= image_tag "note2.jpg" ,class:"book"%>
    </div>
	<div class="col-md-4">
	    <div class="note-info">
          
             <b><h3>Create a New Account</h3></b></br>
  			<strong><%= link_to "Log In", new_user_session_path ,class: "btn-custom"%></strong>
  			<strong><%= link_to "Sign UP", new_user_registration_path ,class: "btn-custom"%></strong>
  		 
  		 </div>
    </div>
</div>

app/views/noteskeeps/_form.html.erb
<div class="reviews">
<%= simple_form_for @note do |f| %>
 <h4> <b><%= f.input :title, label: "Note Title" %></b></h4>
 <h4><b><%="Description"%></b><%= f.input :description,label: false,:input_html => {:rows => 10} %></h4>
     <%= hidden_field_tag "user_shared_by",current_user.id %>
    <h4><b><%= "Tagging User"%>&nbsp&nbsp&nbsp&nbsp</b><%= select_tag "user_shared_to", options_from_collection_for_select(@user, "id", "email"),prompt: "Select something" %></h4>
     <h4><b><%="Tagging Type" %>&nbsp&nbsp&nbsp&nbsp</b><%= select_tag "share_type", options_for_select([ "read", "update","delete","share" ]),prompt: "Select" %></h4>
 

         <div class="links-btn-group">
              <h3>   <%= f.button :submit ,"submit" ,class: "btn-custom" %></h3>
              <h3  align="center"> <%= link_to "BACK",noteskeeps_path ,class: "btn-custom"%></h3>
        </div>
<% end %>

 </div>

app/views/noteskeeps/edit.html.erb
<h1>Edit Notes</h1>
<%= render 'form'%>

app/views/noteskeeps/index.html.erb
<div class="row">
    	<div class="col-md-6 col-md-offset-3">
<div class="reviews">
<h1 align="center"><b>Notes</b></h1>
</div>
    </div>
</div>
<div class="row">
    	<div class="col-md-6 col-md-offset-3">
	         <div class="note-info">
	                    <div class="row">
                         <div class="col-md-4"><h4><b><%="TITLE OF NOTE"%></d></h4></div>
                         <div class="col-md-4"><h4><b><%="DATE OF CREATION" %></d></h4></div>
                         </div>
	             
	             
                    <% @notes.each do |note|%>
                         <div class="row">
                         <div class="col-md-4"><h4><b><%=link_to note.title, noteskeep_path(note)%></d></h4></div>
                         <div class="col-md-4"><h4><b><%=note.created_at.strftime("%Y-%m-%d") %></d></h4></div>
                         </div>
                    <%end%>

                <div class="links-btn-group">
                <h3 align="center">  <%= link_to "ADD Note",new_noteskeep_path ,class: "btn-custom"%>  </h3>
                </div> 

	    </div>
    </div>
</div>


 

app/views/noteskeeps/new.html.erb
<div class="row">
    	<div class="col-md-6 col-md-offset-3">
            <div class="reviews">
                   <h2 align="center"> <b>Creating Notes</b></h2>
                    <%= render 'form'%>

  		 </div>
    </div>
</div>

app/views/noteskeeps/show.html.erb
<% if user_signed_in? %>

       <% @share.each do |share| %>
       
       <%if share.user_shared_by == current_user.id %>
       <div class="row">
    	<div class="col-md-6 col-md-offset-3">
            <div class="reviews">
                           <h1> <%= @note.title %></h1>
                           <p> <%= @note.description %></p>
                       <div class="links-btn-group">                
                        <%= link_to "Edit", edit_noteskeep_path(@note),class: "btn-custom"%>
                       <%= link_to "Delete",noteskeep_path(@note),method: :delete, data: { confirm: "Are you sure?"},class: "btn-custom"%>
                        <%= link_to "Share", edit_noteskeep_path(@note),class: "btn-custom"%>
                        <h5 align="center">  <%= link_to "BACK",noteskeeps_path ,class: "btn-custom2"%>  </h5>
                        
                    </div>
    	    </div>
        </div>
    </div>   

      
       
       <%elsif share.user_shared_to == current_user.id and share.share_type == "read"  %>
               <div class="row">
            	<div class="col-md-6 col-md-offset-3">
                    <div class="reviews">
                      <h1> <%= @note.title %></h1>
                    <p><%= @note.description %></p>
                    <div class="links-btn-group"> 
                    <h5 align="center">  <%= link_to "BACK",noteskeeps_path ,class: "btn-custom2"%>  </h5>
                    
                    </div>
            </div>
        </div>
    </div>  
       
       <%elsif share.user_shared_to == current_user.id and share.share_type == "update"  %>
       
        <h1> <%= @note.title %></h1>
       <%= @note.description %>
       <%= link_to "Edit", edit_noteskeep_path(@note)%>
              <div class="row">
    	<div class="col-md-6 col-md-offset-3">
            <div class="reviews">
                           <h1> <%= @note.title %></h1>
                           <p> <%= @note.description %></p>
                       <div class="links-btn-group">                
                        <%= link_to "Edit", edit_noteskeep_path(@note),class: "btn-custom"%>
                        <h5 align="center">  <%= link_to "BACK",noteskeeps_path ,class: "btn-custom2"%>  </h5>
                    </div>
    	    </div>
        </div>
    </div> 
       
       
       
       <%elsif share.user_shared_to == current_user.id and share.share_type == "delete"  %>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
            <div class="reviews">
                           <h1> <%= @note.title %></h1>
                           <p> <%= @note.description %></p>
                       <div class="links-btn-group">                
                       <%= link_to "Delete",noteskeep_path(@note),method: :delete, data: { confirm: "Are you sure?"},class: "btn-custom"%>
                       <h5 align="center">  <%= link_to "BACK",noteskeeps_path ,class: "btn-custom2"%>  </h5>
                    </div>
    	    </div>
        </div>
    </div> 
       <%elsif share.user_shared_to == current_user.id and share.share_type == "share"  %>
           <div class="row">
    	        <div class="col-md-6 col-md-offset-3">
                    <div class="reviews">
        <h4 align="center"> <b><%= @note.title %></b></h4>
        <p> <%= @note.description %></p>
         
        <%= form_tag(:controller => "noteskeeps", :action => "share_note") do %> 
        
            <%= hidden_field_tag "notekeep_id",@note.id %>
            <%= select_tag "user_shared_to", options_from_collection_for_select(@user, "id", "email"),prompt: "Select User" %>
            <%= hidden_field_tag "user_shared_by",current_user.id %>
            <%= select_tag "share_type", options_for_select([ "read", "update","delete","share" ]),prompt: "Select Type" %></br>
             <div class="links-btn-group"> 
            </br> <%= submit_tag "share" ,class: "btn-custom"%> 
             </div>
            <% end %>
        <%else%>
        <%flash[:alert] = "Notes is not shared with you !!!!!!!!!!!!!."%>
       <h3 align="center">  <%= link_to "BACK",noteskeeps_path ,class: "btn-custom2"%>  </h3>
       <%end%>
       
    <%end%>
 <%end%>
 
     	    </div>
        </div>
    </div> 